[ELF] - An attemp to fix builld bit after r368260
BB: http://lab.llvm.org:8011/builders/lld-perf-testsuite/builds/17577/steps/build-bin%2Flld/logs/stdio

The error is:
/home/buildslave/slave_as-bldslv8/lld-perf-testsuite/llvm/include/llvm/Object/ELF.h:67:14:
error: 'static' function 'defaultWarningHandler' declared in header file should be declared 'static inline' [-Werror,-Wunneeded-internal-declaration]
static Error defaultWarningHandler(const Twine &Msg) { return createError(Msg); }
             ^

git-svn-id: https://llvm.org/svn/llvm-project/llvm/trunk@368262 91177308-0d34-0410-b5e6-96231b3b80d8
(cherry picked from commit c35034a238969bf483c5d164372a4d3400f457a3)